### ISSUE TITLE
Recursive Groups

### ISSUE THREAD

**Issue by corbinucode** [milux/ctldap#3] opened 2017-12-21 15:29 UTC
First of all: thank you for the great and very useful tool.

Testing with JXplorer suggests that groups are listed recursively:
![selection_404](https://user-images.githubusercontent.com/14301506/34262170-dbae2038-e66b-11e7-93a7-2e74ed24e079.png)

As of now there is no urgent requirement to get this issue resolved. 
Thank you for looking into it.

Cheers
Ulrich

**Comment by milux** [comment] 2017-12-21 21:51
Hello Ulrich,
sorry to say that, but I can neither reproduce nor confirm the issue you are describing.
When doing a tree search cn=* with JXplorer, it lists all available groups and users without any flaws.
Further, there cannot be any recursion, as groups only contain users as "uniquemember" attribute members, and users only contain groups as "memberof" attribute members.
Thus, whatever you're experiencing seems very strange... could you give me more information about this?
Best, Michael

**Comment by corbinucode** [comment] 2017-12-22 09:17
Hi Michael,

Thank you for your response.
I can confirm that the tree search with cn=* returns the expected result. I see the "recursion" when I connect as depicted in the screen shot below:
![selection_410](https://user-images.githubusercontent.com/14301506/34292434-31205910-e701-11e7-9852-47f831e942b7.png)

Do you see a problem there?

Cheers, Ulrich

**Comment by milux** [comment] 2017-12-22 11:26
OK, now we're talking... Since this is not a very urgent issue, I will have a look at it as soon as my time allows it. Funny though... I can't even imagine where this side effect comes from. ^^

**Comment by milux** [comment] 2020-03-15 18:30
Fixed in develop. For some reason, the user will still have an empty leaf with its own CN. I really can't figure out where this is coming from. It could as well be a bug of JXplorer, which is more than 6 years old now.

**Closed as completed by milux** 2020-03-15 18:30 UTC
Labels: bug
